package com.example.pdvmaquineta.domain.authorization

enum class Permission {
    AUTHORIZE_DISCOUNT,
    AUTHORIZE_CANCELLATION,
    AUTHORIZE_CASH_WITHDRAWAL,
    AUTHORIZE_CASH_SUPPLY,
    VIEW_OPERATIONAL_REPORTS,
    VIEW_FULL_REPORTS,
    MANAGE_USERS,
    MANAGE_PRODUCTS,
    MANAGE_TERMINALS,
    MANAGE_PAYMENT_METHODS,
    MANAGE_INTEGRATIONS,
    MANAGE_LOYALTY,
    MANAGE_BUSINESS_CONFIG
}
